const createContent = () => {
  const content = document.createElement('div');
  content.textContent = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque in dictum non consectetur. Velit sed ullamcorper morbi tincidunt. Cursus turpis massa tincidunt dui ut. Nullam non nisi est sit amet facilisis magna etiam. Nec feugiat in fermentum posuere. Diam sollicitudin tempor id eu. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Leo duis ut diam quam nulla porttitor massa id. Arcu ac tortor dignissim convallis aenean et tortor at. Sagittis aliquam malesuada bibendum arcu vitae. Convallis a cras semper auctor neque vitae tempus. Aliquam ut porttitor leo a diam sollicitudin tempor id. Maecenas pharetra convallis posuere morbi leo urna molestie.'

  + 'Libero volutpat sed cras ornare arcu dui vivamus. Quis vel eros donec ac. Volutpat est velit egestas dui id ornare arcu odio ut. Faucibus et molestie ac feugiat sed lectus. Sit amet commodo nulla facilisi. Eu turpis egestas pretium aenean pharetra magna. Pellentesque diam volutpat commodo sed egestas. Aliquam purus sit amet luctus venenatis. Volutpat est velit egestas dui id ornare arcu. Nibh tortor id aliquet lectus. Eu tincidunt tortor aliquam nulla. Quis commodo odio aenean sed adipiscing. Viverra adipiscing at in tellus integer feugiat scelerisque varius.'

  + 'Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Id venenatis a condimentum vitae. Tristique magna sit amet purus gravida quis. Amet venenatis urna cursus eget nunc scelerisque. Tortor dignissim convallis aenean et tortor at. Auctor neque vitae tempus quam pellentesque nec. Mauris rhoncus aenean vel elit scelerisque mauris. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras. At augue eget arcu dictum varius duis. Et netus et malesuada fames ac. Ornare suspendisse sed nisi lacus sed. Porttitor rhoncus dolor purus non enim. Nunc pulvinar sapien et ligula ullamcorper. Potenti nullam ac tortor vitae purus faucibus. Amet nulla facilisi morbi tempus iaculis urna. Eu facilisis sed odio morbi quis commodo odio aenean.'

  + 'Velit ut tortor pretium viverra suspendisse potenti. Quam vulputate dignissim suspendisse in est. Cras tincidunt lobortis feugiat vivamus at augue. At consectetur lorem donec massa sapien faucibus et molestie ac. Ultricies mi eget mauris pharetra et ultrices. Sed euismod nisi porta lorem. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Sed id semper risus in hendrerit. Integer vitae justo eget magna fermentum iaculis eu. Vivamus at augue eget arcu dictum varius duis. Egestas sed sed risus pretium quam vulputate. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Neque convallis a cras semper auctor neque vitae tempus. Lacus laoreet non curabitur gravida arcu ac.'

  + 'Ut morbi tincidunt augue interdum velit. Et magnis dis parturient montes nascetur ridiculus mus. Congue quisque egestas diam in arcu cursus euismod. Etiam erat velit scelerisque in dictum. In ante metus dictum at. Ligula ullamcorper malesuada proin libero nunc consequat. Turpis in eu mi bibendum neque. Mauris pellentesque pulvinar pellentesque habitant. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Dignissim suspendisse in est ante in nibh mauris cursus. Semper eget duis at tellus at urna condimentum mattis. Tincidunt nunc pulvinar sapien et. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Aliquet nibh praesent tristique magna sit amet purus.';

  return content;
};

export default createContent;
